### ISSUE TITLE
ModuleNotFoundError                       Traceback (most recent call last) <ipython-input-20-fd28d0a39720> in <module> ----> 1 import tensorflow as tf       2 from object_detection.utils import config_util       3 from object_detection.protos import pipeline_pb2       4 from google.protobuf import text_format  ModuleNotFoundError: No module named 'tensorflow'ModuleNotFoundError                       Traceback (most recent call last) <ipython-input-20-fd28d0a39720> in <module> ----> 1 import tensorflow as tf       2 from object_detection.utils import config_util       3 from object_detection.protos import pipeline_pb2       4 from google.protobuf import text_format  ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by arifyunan360** [nicknochnack/RealTimeObjectDetection#2]
Hi nick,  while I'm trying to pass the step 5, Update Config for Transfer Learning in your tutorial notebook, I got this error

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-fd28d0a39720> in <module>
----> 1 import tensorflow as tf
      2 from object_detection.utils import config_util
      3 from object_detection.protos import pipeline_pb2
      4 from google.protobuf import text_format

ModuleNotFoundError: No module named 'tensorflow'

i already followed your step in installing microsoft c++, protoc, and also the setup requirements like in this videos:https://www.youtube.com/watch?v=dZh_ps8gKgs&feature=youtu.be

can you help me with this issue?

The only thing that I did not install is the cuda and cudnn as O dont have nvidia gpu..

I'm waiting for your response 

Thank you

**Comment by sumitsamsharma** [comment]
how did you resolve this? I am getting the same error
